### ISSUE TITLE
Hot reloading not reliable

### ISSUE THREAD

**Issue by zigomir** [vercel/micro-dev#23]
Hi! First thanks for this rally fine separation of `micro` and `micro-dev`, I think it's neat!

Now while using `mico-dev` it happens to me pretty often that it won't pick up file changes. (I'm using node v8.3.0 on latest macOS).

Usually first file changes are recognized and server is restarted but after a while it just stops re-starting. 

Simplest way to reproduce I found up until now is to open `index.js` file in any editor and just keep saving it (or just hold down cmd + s for few seconds). After few saves `micro-dev` will stop restarting a server. (It happens also when normally editing code and saving).

package.json
```json
{
  "name": "micro-dev-restart-issue",
  "main": "index.js",
  "scripts": {
    "dev": "micro-dev"
  },
  "devDependencies": {
    "micro-dev": "^1.2.0"
  }
}
```

index.js
```js
exports.default = (req, res) => {
  res.end('hey')
}
```

**Comment by zigomir** [comment]
@leo can't you reproduce it with holding cmd + s for few seconds? I can reproduce it this way ever time.

**Comment by leo** [comment]
@zigomir That doesn't sound like a real-world scenario. The system might be suffering if the file is being updated too fast. In turn, we might have to implement a threshold.

**Comment by zigomir** [comment]
This reproduction is not real-world, but I also get same issue whenever I "normally" edit my code when editor saves whenever I cmd + tab to other windows etc.

**Comment by shigurenimo** [comment]
There is an output "Restarted!", But it is not functioning. I'm using node v8.2.0 on latest macOS.

**Comment by tungv** [comment]
I might be experiencing the same issue.

When I tried to log `toDelete`, I got the relative paths (for example `src/abc.js` or `build/abc.js`). I don't believe `require.resolve(item)` can resolve those paths. In fact, it always threw and `continue`. Thus, `delete` command after that never ran.

I'm using node 8.2.1

I'm pretty sure hot reload is reliably not working at all (at least on node 8.2.1) and I made a PR attempting to fix this #29

**Comment by tungv** [comment]
I made a PR attempting to fix this https://github.com/zeit/micro-dev/pull/29

**Comment by tungv** [comment]
I'm pretty sure hot reload is reliably not working (at least on node 8.2.1)

**Comment by leo** [comment]
Should be fixed in https://github.com/zeit/micro-dev/pull/29. Releasing soon!

**Comment by tungv** [comment]
@zigomir I can't reproduce your reported situation. can you create a git repo that can reproduce it?

**Comment by zigomir** [comment]
@tungv 

```bash
echo 'exports.default = (req, res) => {
  res.end(`test`)
}' >> index.js

echo '{
  "name": "micro-dev-restart-issue",
  "main": "index.js",
  "scripts": {
    "dev": "micro-dev"
  },
  "devDependencies": {
    "micro-dev": "^1.2.2"
  }
}' >> package.json

npm install
```

most easily reproducible with `vscode` editor, but I can still reproduce using vim.

**Comment by tungv** [comment]
I tried to edit it in atom/vscode and it worked very well

![image](https://user-images.githubusercontent.com/1922462/30240489-5bb2265c-959b-11e7-95ef-9e71e83c7fe8.png)

**Comment by zigomir** [comment]
For sure it works for one change. Try making more, up to 10+ saves. It always stops working after few saves for me.

**Comment by tungv** [comment]
now I can reproduce the behavior (10+ continuous saves) in vscode and atom. I think until this is fixed, the best way is not to hit cmd+s that often 😺

**Comment by tungv** [comment]
I think I figured out what was wrong. Will make a PR when I get to my laptop

**Comment by tungv** [comment]
this PR https://github.com/zeit/micro-dev/pull/34 should fix the problem @zigomir stated
